name: ClaudeChat
options:
  bundleIdPrefix: com.claude
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
  createIntermediateGroups: true

packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.3.0"

targets:
  # macOS Target
  ClaudeChat:
    type: application
    platform: macOS
    sources:
      - path: Shared
        excludes:
          - "**/*.plist"
      - path: macOS
        excludes:
          - Info.plist
          - ClaudeChat.entitlements
      - path: Shared/Resources
        buildPhase: resources
    dependencies:
      - package: MarkdownUI
    info:
      path: macOS/Info.plist
      properties:
        LSUIElement: true
        CFBundleDisplayName: ClaudeChat
        NSAppleEventsUsageDescription: ClaudeChat needs to send Apple Events.
        NSAppTransportSecurity:
          NSExceptionDomains:
            tail11899.ts.net:
              NSIncludesSubdomains: true
              NSExceptionAllowsInsecureHTTPLoads: true
    entitlements:
      path: macOS/ClaudeChat.entitlements
    settings:
      INFOPLIST_FILE: macOS/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.claude.ClaudeChat
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      CODE_SIGN_ENTITLEMENTS: macOS/ClaudeChat.entitlements
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: "Apple Development"
      DEVELOPMENT_TEAM: 6237SR7A22
      ENABLE_APP_SANDBOX: NO
      ENABLE_HARDENED_RUNTIME: NO
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  # iOS Target
  ClaudeChat-iOS:
    type: application
    platform: iOS
    sources:
      - path: Shared
        excludes:
          - "**/*.plist"
      - path: iOS
        excludes:
          - Info.plist
          - ClaudeChat-iOS.entitlements
      - path: Shared/Resources
        buildPhase: resources
    dependencies:
      - package: MarkdownUI
    info:
      path: iOS/Info.plist
      properties:
        CFBundleDisplayName: ClaudeChat
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSExceptionDomains:
            tail11899.ts.net:
              NSIncludesSubdomains: true
              NSExceptionAllowsInsecureHTTPLoads: true
    entitlements:
      path: iOS/ClaudeChat-iOS.entitlements
    settings:
      INFOPLIST_FILE: iOS/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.claude.ClaudeChat
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      TARGETED_DEVICE_FAMILY: "1,2"
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: "Apple Development"
      DEVELOPMENT_TEAM: 6237SR7A22
      CODE_SIGN_ENTITLEMENTS: iOS/ClaudeChat-iOS.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
